### ISSUE TITLE
Open dialog to talk

### ISSUE THREAD

**Issue by yuristsepaniuk** [VladislavKarpovich/NewsPortal#2]
Влад, привет! Тут просто мысли вслух, но тема интересная! Почитай плиз файлик и скажи что думаешь, похожую идею ты предлагал?

[dateindex.txt](https://github.com/VladislavKarpovich/NewsPortal/files/914466/dateindex.txt)

**Comment by VladislavKarpovich** [comment]
Да, подобие такого дерева. Очень понравилась реализация моментального выбора нужных элементов с помощью Object.keys и noTagIndexCornerYears.
    Но раз пошла речь о нескольких индексах и составных индексах, то возникают ещё некоторые проблемы фильтрации. В тз у нас должна быть реализована фильтрация по тегам, дате и автору. Вопрос в том, не будут ли слишком громоздкими составные индексы, ведь поддерживать код становится сложнее?
    Можно реализовать индексы по каждому критерию поиска отдельно, но тогда придётся искать пересечение ids, что может быть затратным по времени, стоит ли оно того?
Как лучше поступить?

**Comment by yuristsepaniuk** [comment]
Отлично! Возникают абсолютно правильные вопросы, это здорово! При добавлении нового индекса именно эти вопросы и должны возникать, давай чуть глубже:
1. Сколько памяти этот индекс будет кушать? Если он не умещается в RAM, тогда нужно загружать в RAM часть индекса, делать поиск по части, создавать промежуточный результат поиска, сохранять его куда-то, потом загружать вторую часть индекса, искать новости по нему тоже и тд.
2. Как быстро происходит операция удаления и операция создания новой статьи при текущем индексе? Естественно операция поиска новости или новостей по критерию должна происходить быстро, иначе нет смысла в индексах, но тут мы платим цену по долгому созданию или удалению. Поэтому часто задают вопрос, какие операции в системе более частые? Чтение или запись. Как практика показывает, запись - реже. Как и в нашем случае. Тем не менее, если наш индекс полностью помещается в памяти RAM, то при текущей имплементации запись будет быстрой.
2.1. Ты добавляешь новость и знаешь какие теги ты на нее навешиваешь и под какой датой создается новость? По бакету ты легко добавишь ее во все возможные индексы. Если ты редактируешь новость, то нужно предоставить какие теги были, какие теги стали. Поэтому и важно иметь возможность по primary key --> id легко найти старую новость в базе, доточить индекс и записывать новую статью в источник, только после стабилизации индекса. Но существуют и оптимистичные варианты, когда индекс стабилизируют когда-нибудь потом, в этом случае нужно хранить историю изменений, чтобы раз в неделю прогнать полную реиндексацию данных. Оптимистика подразумевает, что твой поиск не будет предоставлять всегда актуальную информацию, но через некоторое время все подхватится.
2.2. Удаление новости - очень дешево --> поправить индекс, убрать данные, но это в нашем случае, не всегда удаление работает быстро.

Вопрос, что это труднозатратно постоянно обновлять свой код, согласен. Но почему бы не сделать DataAccessLevel часто называют DAO, чтобы работать с данными? Твоя программа остается неизменной, только сервис меняется. Я предлагаю поиграться с индексами настолько, насколько позволит время и силы, чтобы просто понимать вопросы, которые будут появляться по ходу.

Когда Леша Чумаков прочитает лекцию по Mongo, станет понятно, что это все есть в монге, но наша задача понять, что дорого, а что дешево и почему. Когда студенты прокачаются, нужно будет пояснить где Mongo не справляется, тут появляется ElasticSearch или Solr. Все программисты, работающие с базами данных, должны думать о индексах. Но чтобы о них думать, нужно знать, какие запросы будет выполнять программа, чтобы начинать строительство.

**Comment by yuristsepaniuk** [comment]
Чуть не забыл! Есть такое понятие full scan! Ты создаешь отдельные индексы для разных критериев! Один для поиска только по датам, второй индекс где поиск только по тегам, третий по тегам вместе с датами, четвертый по авторам, возможны вариации авторов с чем-нибудь еще. Что делать если фильтр сложный? Выбираешь из фильтра самый крутой критерий и начинаешь с него, получаешь результат, который полностью сканируешь (full scan на остальные критерии поиска). Редко получается результат после первого индекса, который можно суметь прогнать через еще один индекс, это тема сложная, поэтому чаще всего в базах ты увидишь после применения одного индекса full scan. Вообще я не ожидал, что у вас такой сложный таск. Поэтому я предлагаю построить парочку индексов, например простейшие по тегам, а если в критерии приваливает с Date Range, делай фул скан, но после применения индекса по тегам. Покачайся!

**Comment by VladislavKarpovich** [comment]
Всё понял) спасибо, буду реализовывать.

**Comment by chirichok98** [comment]
@yuristsepaniuk , добрый вечер!
Видел вашу "дискуссию" с людьми с потока. Была замечена важность code style. 
Очень переживаю, что в моем репозитории нет замечаний.
У меня все плохо? Если да, то возможно ли еще что-то  исправить?

P.S.  
Извиняюсь, что пишу здесь. Не знал, как еще можно связаться.
